version: '3.7'
services: 
    postgres:
        image: postgres:14.1
        restart: always
        environment: 
            - POSTGRES_DB=orders
            - POSTGRES_USER=testuser
            - POSTGRES_PASSWORD=testpassword
        logging:
          options: 
            max-size: 10m
            max-file: "3"
        ports: 
          - '5432:5432'
        volumes:
          - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql